version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai_tg_writer_postgres
    environment:
      - POSTGRES_DB=ai_tg_writer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - ai_tg_writer_network

  redis:
    image: redis:7-alpine
    container_name: ai_tg_writer_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ai_tg_writer_network

volumes:
  postgres_data:
    driver: local

networks:
  ai_tg_writer_network:
    driver: bridge
